### ISSUE TITLE
JCon reports back to JOSS reviews.

### ISSUE THREAD

**Issue by vchuravy** [xuanxu/theoj#6]
Instead of reporting that the pipeline failed on the JCon review repository the failure get's reported in joss-reviews.

https://github.com/JuliaCon/proceedings-papers/issues/64#issuecomment-1302437320

**Comment by xuanxu** [comment]
This happens because the workflows are configured with the wrong values for repositories and journal data.

For example: [GH_REPO here](https://github.com/JuliaCon/proceedings-papers/blob/master/.github/workflows/draft-paper.yml#L21) should point to the JCon repo, and [journal here](https://github.com/JuliaCon/proceedings-papers/blob/master/.github/workflows/draft-paper.yml#L30) and [branch_prefix](https://github.com/JuliaCon/proceedings-papers/blob/master/.github/workflows/draft-paper.yml#L36) should be jcon instead of joss. 
Same with the [other workflows](https://github.com/JuliaCon/proceedings-papers/tree/master/.github/workflows).
